config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "departments#index"

  resources :departments do
    resources :store_items
  end

  resources :store_items do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :store_items
end

app/models/store_item.rb
class StoreItem < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index
    @departments = Department.all
  end

  def show
    @department = Department.find(params[:id])
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(departments_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    if(@department.update(departments_params))
      redirect_to departments_params
    else
      render :edit
    end
  end

  def destroy
    Department.find(params[:id]).destroy
    # @department.destroy
    redirect_to departments_path
  end

  private
  def departments_params
    params.require(:department).permit(:name)
  end
end

app/controllers/store_items_controller.rb
class StoreItemsController < ApplicationController
  def index
    @store_items = Store_item.all
  end

  def show
    @store_item = Store_item.find(params[:id])
  end

  def new
    @store_item = Store_item.new
  end

  def create 
    @store_item = Store_item.new(store_item_params)
    
    if @store_item.save
      redirect_to store_item_path
    else
      render :new
    end
  end

  def edit
    @store_item = Store_item.find(params[:id])
  end

  def destroy
    @store_item.destroy
    redirect_to store_item_path
  end

  private
  def store_item_params
    params.require(:Store_item).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/store_items_helper.rb
module StoreItemsHelper
end

app/views/departments/_form.html.erb
<h1> form

app/views/departments/edit.html.erb
<h1>Edit Department</h1>
<%= form_for @department do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name%>
  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1>Departments:</h1>
<%= link_to 'Click to Create New Department', new_department_path %>
<ul>
  <% @departments.each do |department| %>
    <li><%= link_to department.name %></li>

    <%= link_to 'Show Department', department_path(department)%>
    <%= link_to 'Edit Department', edit_department_path(department)%>
    <%= link_to 'Delete Department', department, method: :delete %>
  <% end %>
   
</ul>

app/views/departments/new.html.erb
<h1>New Department</h1>
<%= form_for @department do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/departments/show.html.erb
<h1> Department Information</h1>
<h1><%= @department.name %></h1>


<p>What would you like to do?</p>
<%= link_to 'View Store Items', department_store_items_path(@department) %>
<br />
<%= link_to 'Edit Store Items', edit_store_item_path(@department) %>
<br />
<%= link_to 'Delete Department', @department, method: :delete %>
<%= link_to 'Back', departments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/store_items/edit.html.erb
<h1>Edit Store Items</h1>
<%= form_for @store_item do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name%>
  <%= f.submit %>
<% end %>

app/views/store_items/index.html.erb
<h1>Store Items:</h1>
<%= link_to 'Click to Create New Items', new_store_item_path %>
<ul>
  <% @store_items.each do |store_item| %>
    <li><%= link_to store_item.name %></li>

    <%# <%= link_to 'Show Item', store_item_path(department)%>
    <%# <%= link_to 'Edit Item', edit_store_item_path(department)%>
    <%# <%= link_to 'Delete Item', store_item, method: :delete %> 
  <% end %>
   
</ul>

app/views/store_items/new.html.erb
<h1>Add New Store Item </h1>
<%= form_for @store_item do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/store_items/show.html.erb
<h1><%= @department.name %> - <%= @store_item.name %></h1>
<h1><%= @store_item.name %></h1>
<%= link_to 'Edit Item', edit_store_items_path([@department, @store_item])%>
<%= link_to 'Delete Item', [@department, @store_item], method: :delete %>
<%= link_to 'Back to Items', store_items_path(@store_item) %>
<%= link_to 'New Item', new_store_item_path(@store_item) %>